-- ============================================================
-- Cuidando do Lar — IPVSP
-- Setup do Supabase: tabelas, índices, RLS e Realtime
-- ============================================================
-- Como executar:
--   1) Abra o Supabase Dashboard do seu projeto
--   2) Menu lateral → SQL Editor → New query
--   3) Cole TODO este arquivo e clique em "Run"
-- ============================================================

-- ----------- Tabela: escalas (cuidadores por domingo) -----------
create table if not exists public.escalas (
  id          bigint generated by default as identity primary key,
  data        date        not null,
  horario     text        default '09h30',
  pessoa1     text,
  pessoa2     text,
  observacao  text,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create index if not exists idx_escalas_data on public.escalas(data);

-- ----------- Tabela: estoque -----------
create table if not exists public.estoque (
  id          bigint generated by default as identity primary key,
  nome        text        not null,
  categoria   text        not null check (categoria in ('limpeza','comes_bebes')),
  qtd         text,
  observacao  text,
  urgente     boolean     default false,
  status      text        default 'pendente' check (status in ('pendente','comprado')),
  autor       text,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create index if not exists idx_estoque_categoria on public.estoque(categoria);
create index if not exists idx_estoque_status    on public.estoque(status);

-- ----------- Trigger updated_at -----------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_escalas_updated_at on public.escalas;
create trigger trg_escalas_updated_at
  before update on public.escalas
  for each row execute function public.set_updated_at();

drop trigger if exists trg_estoque_updated_at on public.estoque;
create trigger trg_estoque_updated_at
  before update on public.estoque
  for each row execute function public.set_updated_at();

-- ----------- Row Level Security (acesso aberto) -----------
-- O site é "aberto para todos" conforme combinado.
-- Qualquer pessoa com a anon key pode ler e escrever.
-- Se quiser apertar depois, troque por policies com auth.uid().

alter table public.escalas enable row level security;
alter table public.estoque enable row level security;

drop policy if exists "escalas_read_all"   on public.escalas;
drop policy if exists "escalas_write_all"  on public.escalas;
drop policy if exists "escalas_update_all" on public.escalas;
drop policy if exists "escalas_delete_all" on public.escalas;

create policy "escalas_read_all"   on public.escalas for select using (true);
create policy "escalas_write_all"  on public.escalas for insert with check (true);
create policy "escalas_update_all" on public.escalas for update using (true) with check (true);
create policy "escalas_delete_all" on public.escalas for delete using (true);

drop policy if exists "estoque_read_all"   on public.estoque;
drop policy if exists "estoque_write_all"  on public.estoque;
drop policy if exists "estoque_update_all" on public.estoque;
drop policy if exists "estoque_delete_all" on public.estoque;

create policy "estoque_read_all"   on public.estoque for select using (true);
create policy "estoque_write_all"  on public.estoque for insert with check (true);
create policy "estoque_update_all" on public.estoque for update using (true) with check (true);
create policy "estoque_delete_all" on public.estoque for delete using (true);

-- ----------- Habilitar Realtime nas duas tabelas -----------
-- (Necessário para os updates em tempo real funcionarem)
alter publication supabase_realtime add table public.escalas;
alter publication supabase_realtime add table public.estoque;

-- ----------- Pronto! -----------
-- Volte ao app, configure config.js com a URL e a anon key,
-- e tudo funcionará em tempo real.
